// Autogenerated file, do no edit

struct FGData {
    float barometric_pressure;	// flightgear property: fıxme
    float external_temperature;	// flightgear property: fıxme
    float wind_direction;	// flightgear property: /environment/wind-from-heading-deg
    float wind_speed;	// flightgear property: /environment/wind-speed-kt
    float director_airspeed;	// flightgear property: /controls/autoflight/speed-select
    float director_vertical_speed;	// flightgear property: /controls/autoflight/vertical-speed-select
    float director_roll;	// flightgear property: /controls/autoflight/bank-angle-select
    float director_altitude;	// flightgear property: /controls/autoflight/altitude-select
    float director_heading;	// flightgear property: /controls/autoflight/heading-select
    bool director_active;	// flightgear property: /controls/autoflight/autopilot[0]/engage
    float voltage_battery;	// flightgear property: fıxme
    float voltage_alternator;	// flightgear property: /controls/engines/engine[0]/generator
    float engine_mixture;	// flightgear property: /controls/engines/engine[0]/mixture
    float engine_egt;	// flightgear property: /engines/engine/egt-degf
    float engine_cht;	// flightgear property: /engines/engine/cht-degf
    float engine_rpm;	// flightgear property: /engines/engine/rpm
    float vertical_speed_fpm;	// flightgear property: /velocities/vertical-speed-fps
    float ground_speed_ms;	// flightgear property: /velocities/fıxme
    float airspeed_kt;	// flightgear property: /velocities/airspeed-kt
    float accel_body_down;	// flightgear property: /accelerations/pilot/z-accel-fps_sec
    float accel_body_right;	// flightgear property: /accelerations/pilot/y-accel-fps_sec
    float accel_body_fwd;	// flightgear property: /accelerations/pilot/x-accel-fps_sec
    float altitude_agl_feet;	// flightgear property: /position/altitude-agl-ft
    float altitude_msl_feet;	// flightgear property: /position/altitude-ft
    double longitude;	// flightgear property: /position/longitude-deg
    double latitude;	// flightgear property: /position/latitude-deg
    float track_heading;	// flightgear property: fıxme
    float true_heading;	// flightgear property: /orientation/heading-deg
    float pitch;	// flightgear property: /orientation/pitch-deg
    float roll;	// flightgear property: /orientation/roll-deg
    unsigned int magic;
};
